[ClassVersion("1.0.0.0"), FriendlyName("cFirewallProfile")]
class Huddle_cFirewallProfile : OMI_BaseResource
{
	[Key, ValueMap{"Domain","Public","Private"}, Values{"Domain","Public","Private"}] String Name;
	[write] boolean Enabled;
};
